### ISSUE TITLE
AiForms.SettingsView crashes on iOS with Xamarin Forms 5

### ISSUE THREAD

**Issue by TrueGeek** [muak/AiForms.SettingsView#149]
### Description

We've getting the error: `Cannot access a disposed Object. Object name 'UIKit.UILabel'`. It occurs when you view a page that contains AiForms.Renderers.SettingsView and then go back in the nav stack from that page. This happens only on iOS and only with XF5.

### Steps to Reproduce

1. Create a new Xamarin Forms project with the default template
2. Change App.xaml.cs to open MainPage with a NavigationPage
3. Create a second page containing a SettingsView
4. Put a button or some way on the second page to do a Navigation.PopAsync

You'll see the error when you go back to the MainPage.

Sample project here so that you don't have to recreate it yourself:
[AiFormsTest.zip](https://github.com/muak/AiForms.SettingsView/files/6132869/AiFormsTest.zip)

### Expected Behavior

No crash

### Actual Behavior

Yes crash

### Platforms

- [ ] Android
- [X] iOS

### Basic Information

- AiForms.SettingsView 1.3.5
- Xamarin.Forms 5.0.0.2012
- Android Support Library Version: N/A
- Affected Devices: all iOS devices

### Reproduction Link

[AiFormsTest.zip](https://github.com/muak/AiForms.SettingsView/files/6132869/AiFormsTest.zip)

### Workaround

Downgrade to Xamarin.Forms 4.8.0.1821

### Full exception stack:

```
  at ObjCRuntime.ThrowHelper.ThrowObjectDisposedException (System.Object o) [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/ThrowHelper.cs:34 
  at ObjCRuntime.NativeObjectExtensions.GetNonNullHandle (ObjCRuntime.INativeObject self, System.String argumentName) [0x0001b] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/INativeObject.cs:29 
  at UIKit.UIStackView.RemoveArrangedSubview (UIKit.UIView view) [0x00005] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/ios/native/UIKit/UIStackView.g.cs:182 
  at AiForms.Renderers.iOS.LabelCellView.Dispose (System.Boolean disposing) [0x0000f] in <eb03a4bd60324a70b9d4a575423232fb>:0 
  at AiForms.Renderers.iOS.CommandCellView.Dispose (System.Boolean disposing) [0x00030] in <eb03a4bd60324a70b9d4a575423232fb>:0 
  at Foundation.NSObject.Dispose () [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSObject2.cs:144 
  at AiForms.Renderers.iOS.SettingsViewRenderer.DisposeSubviews (UIKit.UIView view) [0x00030] in <eb03a4bd60324a70b9d4a575423232fb>:0 
  at AiForms.Renderers.iOS.SettingsViewRenderer.DisposeSubviews (UIKit.UIView view) [0x00019] in <eb03a4bd60324a70b9d4a575423232fb>:0 
  at AiForms.Renderers.iOS.SettingsViewRenderer.Dispose (System.Boolean disposing) [0x000a4] in <eb03a4bd60324a70b9d4a575423232fb>:0 
  at Foundation.NSObject.Dispose () [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSObject2.cs:144 
  at Xamarin.Forms.Platform.iOS.VisualElementPackager.Dispose (System.Boolean disposing) [0x0003f] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementPackager.cs:72 
  at Xamarin.Forms.Platform.iOS.VisualElementPackager.Dispose () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementPackager.cs:40 
  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].Dispose (System.Boolean disposing) [0x00058] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementRenderer.cs:376 
  at Foundation.NSObject.Dispose () [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSObject2.cs:144 
  at Xamarin.Forms.Platform.iOS.VisualElementPackager.Dispose (System.Boolean disposing) [0x0003f] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementPackager.cs:72 
  at Xamarin.Forms.Platform.iOS.VisualElementPackager.Dispose () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementPackager.cs:40 
  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].Dispose (System.Boolean disposing) [0x00058] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementRenderer.cs:376 
  at Foundation.NSObject.Dispose () [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSObject2.cs:144 
  at Xamarin.Forms.Platform.iOS.DisposeHelpers.DisposeModalAndChildRenderers (Xamarin.Forms.Element view) [0x00042] in D:\a\1\s\Xamarin.Forms.Platform.iOS\DisposeHelpers.cs:23 
  at Xamarin.Forms.Platform.iOS.Platform.HandleChildRemoved (System.Object sender, Xamarin.Forms.ElementEventArgs e) [0x00006] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Platform.cs:357 
  at Xamarin.Forms.Element.OnDescendantRemoved (Xamarin.Forms.Element child) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:584 
  at Xamarin.Forms.Element.OnChildRemoved (Xamarin.Forms.Element child) [0x0001f] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:339 
  at Xamarin.Forms.VisualElement.OnChildRemoved (Xamarin.Forms.Element child) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:825 
  at Xamarin.Forms.Page.OnInternalRemoved (Xamarin.Forms.VisualElement view) [0x00013] in D:\a\1\s\Xamarin.Forms.Core\Page.cs:508 
  at Xamarin.Forms.Page.InternalChildrenOnCollectionChanged (System.Object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e) [0x0002c] in D:\a\1\s\Xamarin.Forms.Core\Page.cs:478 
  at System.Collections.ObjectModel.ObservableCollection`1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs e) [0x00018] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/System.ObjectModel/src/System/Collections/ObjectModel/ObservableCollection.cs:263 
  at System.Collections.ObjectModel.ObservableCollection`1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedAction action, System.Object item, System.Int32 index) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/System.ObjectModel/src/System/Collections/ObjectModel/ObservableCollection.cs:338 
  at System.Collections.ObjectModel.ObservableCollection`1[T].RemoveItem (System.Int32 index) [0x00021] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/System.ObjectModel/src/System/Collections/ObjectModel/ObservableCollection.cs:182 
  at System.Collections.ObjectModel.Collection`1[T].Remove (T item) [0x00027] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/Common/src/CoreLib/System/Collections/ObjectModel/Collection.cs:128 
  at Xamarin.Forms.NavigationPage.Xamarin.Forms.INavigationPageController.RemoveAsyncInner (Xamarin.Forms.Page page, System.Boolean animated, System.Boolean fast) [0x000e7] in D:\a\1\s\Xamarin.Forms.Core\NavigationPage.cs:359 
  at Xamarin.Forms.Platform.iOS.NavigationRenderer.UpdateFormsInnerNavigation (Xamarin.Forms.Page pageBeingRemoved) [0x00072] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\NavigationRenderer.cs:827 
  at Xamarin.Forms.Platform.iOS.NavigationRenderer+ParentingViewController.DidMoveToParentViewController (UIKit.UIViewController parent) [0x0003a] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\NavigationRenderer.cs:1490 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021 
  at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSAction.cs:178 
--- End of stack trace from previous location where exception was thrown ---

  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:65 
  at AgentApp.iOS.Application.Main (System.String[] args) [0x00001] in /Users/dean/Code/AgentApp/AgentApp.iOS/Main.cs:24 
```

**Comment by mphill** [comment]
I am having this issue as well.  This is a  work around: https://github.com/muak/AiForms.SettingsView/compare/master...mphill:master.  It looks like there was some change to the Xamarin intervals where objects that derive from the `Element` class are being automatically disposed now.  I'd issue a PR but I think it would potentially create some messy memory management for versions before Xamarin Form 5.0

**Comment by muak** [comment]
@TrueGeek @mphill 
Thank you for your report.

This issue was fixed.
Thanks.

**Comment by mphill** [comment]
This issue is still present.  You could combine this, https://github.com/muak/AiForms.SettingsView/commit/60972e99dd51778f78dc797ed32fb4533da5c074#diff-c173b2d1a12658be18e89e7b7ce18f9c506e17bd1daa06b6d94834a82eeb7d9e and https://github.com/muak/AiForms.SettingsView/compare/master...mphill:master to resolve. I can create a PR later today if you like.

**Comment by muak** [comment]
@mphill 
Thanks.
Could you create the PR?
Would you please tell me the pattern it crashes even if use #150?

**Comment by mphill** [comment]
Actually, looks there is a new issue introduced with the latest PRs (this issue may actually be resolved):  

`Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at Xamarin.Forms.Shell.GetNavBarIsVisible (Xamarin.Forms.BindableObject obj) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Shell\Shell.cs:105 
  at Xamarin.Forms.Platform.iOS.ShellSectionRenderer+NavDelegate.WillShowViewController (UIKit.UINavigationController navigationController, UIKit.UIViewController viewController, System.Boolean animated) [0x00028] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\ShellSectionRenderer.cs:628 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:65 
  at iOS.Application.Main (System.String[] args) [0x00001] in Main.cs:17
2021-03-15 12:44:41.497653-0500 iOS[94044:38028217] Unhandled managed exception: Object reference not set to an instance of an object (System.NullReferenceException)
  at Xamarin.Forms.Shell.GetNavBarIsVisible (Xamarin.Forms.BindableObject obj) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Shell\Shell.cs:105 
  at Xamarin.Forms.Platform.iOS.ShellSectionRenderer+NavDelegate.WillShowViewController (UIKit.UINavigationController navigationController, UIKit.UIViewController viewController, System.Boolean animated) [0x00028] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\ShellSectionRenderer.cs:628 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:65 
  at iOS.Application.Main (System.String[] args) [0x00001] in`

**Comment by TrueGeek** [comment]
Yeah, I think that's a new issue. The latest NuGet issue fixes the XF5 issue for us. Thank you both so much!

**Comment by mphill** [comment]
@TrueGeek are you using AppShell in your app?

**Comment by RLittlesII** [comment]
@TrueGeek Which version latest on NuGet fixed it?

**Comment by TrueGeek** [comment]
@RLittlesII v1.3.12

**Comment by muak** [comment]
@mphill 
Thanks.

Could you post a new issue and show the reproducible sample?

**Comment by mphill** [comment]
@muak I made a sample, but was unable to reproduce.  Looks like its a bug our my code.  SettingsView appears to work fine now!  Thanks - please close.

**Comment by muak** [comment]
@mphill 
Thank you for confirming!
